services:
  - type: web
    name: n8n-self-host
    env: docker
    plan: free
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-self-host-wfdl.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: your-username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-password
